basePath: /
definitions:
  internal_handler.healthCheckResponse:
    properties:
      instance_id:
        example: instance-123
        type: string
      message:
        example: OK
        type: string
      service_name:
        example: bookmark_service
        type: string
    type: object
info:
  contact: {}
  description: A simple password generator API built with Go and Gin.
  title: EBVN Bookmark API
  version: "1.0"
paths:
  /gen-pass:
    get:
      description: Generates a cryptographically secure random password
      produces:
      - text/plain
      responses:
        "200":
          description: Generated password
          schema:
            type: string
        "500":
          description: Error message
          schema:
            type: string
      summary: Generate a random password
      tags:
      - password
  /health-check:
    get:
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.healthCheckResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Health check
      tags:
      - health_check
swagger: "2.0"
